_core:
  default_config_hash: x6RSyMWd1iQYhYS3zBLWYbRgqKfghEjz5rbA025_uJo
agents:
  -
    id: canvas_component_agent
    contexts: {  }
    always_include: {  }
  -
    id: canvas_template_builder_agent
    contexts: {  }
    always_include:
      - component_generation
      - findrop_key_facts_value_propositions
      - landing_page_funnel_rules
  -
    id: pexels_agent
    contexts: {  }
    always_include: {  }
  -
    id: canvas_ai_orchestrator
    contexts: {  }
    always_include: {  }
  -
    id: information_finder
    contexts: {  }
    always_include: {  }
